;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
+GameplayTagTableList=/Game/Sotu/GameplayTags/DT_AbilityTags.DT_AbilityTags
+GameplayTagTableList=/Game/Sotu/GameplayTags/DT_StateTags.DT_StateTags
+GameplayTagTableList=/Game/Sotu/GameplayTags/DT_WeaponTags.DT_WeaponTags
+GameplayTagTableList=/Game/Sotu/GameplayTags/DT_AttributeTags.DT_AttributeTags
+GameplayTagTableList=/Game/Sotu/GameplayTags/DT_InputTags.DT_InputTags
+GameplayTagTableList=/Game/Sotu/GameplayTags/DT_DataTags.DT_DataTags
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Data.Cooldown",DevComment="")

